// Code generated by Slice Machine. DO NOT EDIT.

import TextSlice from './TextSlice/index.svelte';
import WideImage from './WideImage/index.svelte';

export const components = {
	text_slice: TextSlice,
	wide_image: WideImage
};
