// Code generated by Slice Machine. DO NOT EDIT.

import ContentHighlight from './ContentHighlight/index.svelte';
import TextSlice from './TextSlice/index.svelte';
import WideImage from './WideImage/index.svelte';

export const components = {
	content_highlight: ContentHighlight,
	text_slice: TextSlice,
	wide_image: WideImage
};
