// Code generated by Slice Machine. DO NOT EDIT.

import ContentHighlight from './ContentHighlight/index.svelte';
import Expertise from './Expertise/index.svelte';
import InfoEducationImage from './InfoEducationImage/index.svelte';

export const components = {
	content_highlight: ContentHighlight,
	expertise: Expertise,
	info_education_image: InfoEducationImage
};
