// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Affiliation documents
 */
interface AffiliationDocumentData {
	/**
	 * Title field in *Affiliation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: affiliation.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Link field in *Affiliation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: affiliation.link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Affiliation document from Prismic
 *
 * - **API ID**: `affiliation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AffiliationDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<AffiliationDocumentData>,
	'affiliation',
	Lang
>;

/**
 * Item in *Case Study → Responsibilities*
 */
export interface CaseStudyDocumentDataResponsibilitiesItem {
	/**
	 * Skill field in *Case Study → Responsibilities*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.responsibilities[].skill
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	skill: prismic.SelectField<'UI' | 'UX' | 'Research' | 'Strategy'>;
}

type CaseStudyDocumentDataSlicesSlice = ContentHighlightSlice | TextSliceSlice | WideImageSlice;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
	/**
	 * Title field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Hightlight Image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.hightlight_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hightlight_image: prismic.ImageField<never>;

	/**
	 * Date field in *Case Study*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;

	/**
	 * Affiliation field in *Case Study*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.affiliation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	affiliation: prismic.ContentRelationshipField<'affiliation'>;

	/**
	 * Responsibilities field in *Case Study*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.responsibilities[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	responsibilities: prismic.GroupField<Simplify<CaseStudyDocumentDataResponsibilitiesItem>>;

	/**
	 * Slice Zone field in *Case Study*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CaseStudyDocumentDataSlicesSlice> /**
	 * Meta Description field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: case_study.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: case_study.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CaseStudyDocumentData>,
	'case_study',
	Lang
>;

type HomeDocumentDataSlicesSlice = ContentHighlightSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Landing Image field in *Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.landing_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	landing_image: prismic.ImageField<never>;

	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
	 * Meta Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomeDocumentData>,
	'home',
	Lang
>;

export type AllDocumentTypes = AffiliationDocument | CaseStudyDocument | HomeDocument;

/**
 * Primary content in *ContentHighlight → Primary*
 */
export interface ContentHighlightSliceDefaultPrimary {
	/**
	 * Project field in *ContentHighlight → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_highlight.primary.project
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project: prismic.ContentRelationshipField<'case_study'>;
}

/**
 * Default variation for ContentHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHighlightSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContentHighlightSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ContentHighlight*
 */
type ContentHighlightSliceVariation = ContentHighlightSliceDefault;

/**
 * ContentHighlight Shared Slice
 *
 * - **API ID**: `content_highlight`
 * - **Description**: ContentHighlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHighlightSlice = prismic.SharedSlice<
	'content_highlight',
	ContentHighlightSliceVariation
>;

/**
 * Primary content in *TextSlice → Items*
 */
export interface TextSliceSliceDefaultItem {
	/**
	 * textBox field in *TextSlice → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_slice.items[].textbox
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	textbox: prismic.RichTextField;
}

/**
 * Default variation for TextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<TextSliceSliceDefaultItem>
>;

/**
 * Slice variation for *TextSlice*
 */
type TextSliceSliceVariation = TextSliceSliceDefault;

/**
 * TextSlice Shared Slice
 *
 * - **API ID**: `text_slice`
 * - **Description**: TextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceSlice = prismic.SharedSlice<'text_slice', TextSliceSliceVariation>;

/**
 * Primary content in *WideImage → Primary*
 */
export interface WideImageSliceDefaultPrimary {
	/**
	 * image field in *WideImage → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: wide_image.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for WideImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WideImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<WideImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *WideImage*
 */
type WideImageSliceVariation = WideImageSliceDefault;

/**
 * WideImage Shared Slice
 *
 * - **API ID**: `wide_image`
 * - **Description**: WideImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WideImageSlice = prismic.SharedSlice<'wide_image', WideImageSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			AffiliationDocument,
			AffiliationDocumentData,
			CaseStudyDocument,
			CaseStudyDocumentData,
			CaseStudyDocumentDataResponsibilitiesItem,
			CaseStudyDocumentDataSlicesSlice,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			AllDocumentTypes,
			ContentHighlightSlice,
			ContentHighlightSliceDefaultPrimary,
			ContentHighlightSliceVariation,
			ContentHighlightSliceDefault,
			TextSliceSlice,
			TextSliceSliceDefaultItem,
			TextSliceSliceVariation,
			TextSliceSliceDefault,
			WideImageSlice,
			WideImageSliceDefaultPrimary,
			WideImageSliceVariation,
			WideImageSliceDefault
		};
	}
}
